repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.13.1
        stages: [pre-commit]

  - repo: local
    hooks:
    - id: pytest-check
      stages: [pre-push]
      types: [python]
      name: pytest-check
      entry: python3 tagebbbuch/test_app.py
      language: system